# Generated by Django 5.2.3 on 2026-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(max_length=10),
        ),
    ]
